asm (
    ".global setjmp\n"
    ".type setjmp, \"function\"\n"
    "setjmp:\n"
    "\tmov %rbx, 0x00(%rdi)\n"
    "\tmov %rbp, 0x08(%rdi)\n"
    "\tmov %r12, 0x10(%rdi)\n"
    "\tmov %r13, 0x18(%rdi)\n"
    "\tmov %r14, 0x20(%rdi)\n"
    "\tmov %r15, 0x28(%rdi)\n"
    "\tlea 0x08(%rsp), %rax\n"
    "\tmov %rax, 0x30(%rdi)\n"
    "\tmov (%rsp), %rax\n"
    "\tmov %rax, 0x38(%rdi)\n"
    "\txor %rax, %rax\n"
    "\tret\n"
    "\n"
    ".global longjmp\n"
    ".type longjmp, \"function\"\n"
    "longjmp:\n"
    "\tmov %rdi, %rsp\n"
    "\tmov %rsi, %rax\n"
    "\tpop %rbx\n"
    "\tpop %rbp\n"
    "\tpop %r12\n"
    "\tpop %r13\n"
    "\tpop %r14\n"
    "\tpop %r15\n"
    "\tpop %rdx\n"
    "\tpop %rcx\n"
    "\tmov %rdx, %rsp\n"
    "\tjmp %rcx\n"
);
